/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.net.ServerSocket; 
import java.net.Socket;
import java.util.ArrayList;
import java.security.*;
import javax.crypto.*;
import javax.xml.bind.DatatypeConverter;
/**
 *
 * @author bdavies
 */

public class MainWindowServer extends javax.swing.JFrame implements Runnable
{
    Thread t;
    
    ServerSocket welcomeSocket = null;
    Socket connectionSocket = null;
    
    
    public class User
    {
        String userName;
        String ip;
        int portNo;
        Key sharedKey;
        PublicKey publicKey;
        User(String userName, String userIp, int userPortNo, Key sharedKey, PublicKey publicKey)
        {
            this.userName = userName;
            ip = userIp;
            portNo = userPortNo;
            this.sharedKey = sharedKey;
            this.publicKey = publicKey;
        }
    }
    
    ArrayList<User> usersLoggedOn = new ArrayList();
    
    /**
     * Creates new form MainWindowServer
     */
    public MainWindowServer() 
    {
        initComponents();
        
        t = new Thread(this);
        t.start();
    }
    
    public String encrypt(String toEncrypt, Key key) throws Exception
    {
        byte[] plainText = toEncrypt.getBytes();
        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] cipherText = cipher.doFinal(plainText);
        String s = DatatypeConverter.printBase64Binary(cipherText);
        
        return s;
    }
    
    public Key generateSharedKey() throws Exception
    {
        System.out.println("\nStart generating AES key");
        KeyGenerator keyG = KeyGenerator.getInstance("AES");
        keyG.init(128);
        Key key = keyG.generateKey();
        System.out.println("Finish Generating key");
        return key;
    }
    
    public void consoleMessage(String input)
    {
        jTextArea1.append( input + "\n");
    }
    
    
    //this is an infinite loop that tries to get connections - probably need to make this another thread
    @Override
    public void run()
    {
        try
        {
            //create the welcome socket
            welcomeSocket = new ServerSocket(6889);
            
            boolean inloop = false;
            
            while (true)
            {
                if(!inloop)
                {
                    jTextArea1.append("Welcome to the server!\n");
                    inloop = true;
                }
                
                try
                {
                   connectionSocket = welcomeSocket.accept();
                   jTextArea1.append("User Logging in\n");
                   ServerThread st =  new ServerThread(connectionSocket, this);
                }
                catch(Exception e)
                {
                    jTextArea1.append("User Failed Logging in");
                }
            }
         }
         catch(Exception e)
         {
             jTextArea1.append("Server setup failed " + e.getMessage());
         }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindowServer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
